export const eng={
    login_email_placeholder:'Your email',
    login_password_placeholder:'And your password',
    continue_text:'CONTINUE',
    forgot_password_text:'Forgot password?',
    login_btn:'LOG IN',
    login_text:'Login',
    reset_password_text1:'We\'ve sent a link to',
    reset_password_text2:'to reset your password',
    send_link_again:'Send link again',
    home_screen_welcome:'Hello, ',
    home_screen_project_count1:'You\'ve ',
    home_screen_project_count2:' active projects',
    home_screen_evaluate_btn:'Evaluate',
    home_screen_evaluate_count:' evaluations pending',
    home_screen_improve_btn:'Share idea',
    home_screen_report_btn:'Report issue',
    profile_company:'COMPANY',
    profile_email:'EMAIL',
    profile_logout:'SIGN OUT',
    profile_english:'English',
    profile_finnish:'Finnish',
    ideaview_header:'Ideas',
    ideaview_stage_header:'Stages',
    ideaview_operational_header:'Operational',
    ideaview_phase_header:'Phases',
    ideaview_download_btn:'Download file',
    ideaview_improve_btn:'Improve idea',
    ideaview_report_btn:'Report problem',
};

export const fin={
    login_email_placeholder:'Sähköpostisi',
    login_password_placeholder:'ja salasanasi',
    continue_text:'JATKA',
    forgot_password_text:'Unohtuiko salasana?',
    login_btn:'KIRJAUDU',
    login_text:'Kirjaudu',
    reset_password_text1:'Uusi salasana pitäisi saapua',
    reset_password_text2:'sähköpostiinne',
    send_link_again:'Lähetä salasana uudelleen',
    home_screen_welcome:'Heippa, ',
    home_screen_project_count1:'Sinulla on ',
    home_screen_project_count2:' aktiivista projektia',
    home_screen_evaluate_btn:'Arvioi',
    home_screen_evaluate_count:' arviointia odott',
    home_screen_improve_btn:'Jaa idea',
    home_screen_report_btn:'Ilmoita hidaste',
    profile_company:'YRITYS',
    profile_email:'SÄHKÖPOSTI',
    profile_logout:'KIRJAUDU ULOS',
    profile_english:'English',
    profile_finnish:'Finnish',
    ideaview_header:'Ideat',
    ideaview_stage_header:'Tasot',
    ideaview_operational_header:'Operaatiot',
    ideaview_phase_header:'Osiot',
    ideaview_download_btn:'Lataa aineisto',
    ideaview_improve_btn:'Paranna ideaa',
    ideaview_report_btn:'Ilmoita hidaste',
};